spring.application.name=Online-Voting-System

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/votingdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=X7pL9qW3zT2rY8mF6vN4kJ5hB0cD1xA2uE3tR8wQ9eZ
jwt.expiration=3600000

app.admin.secret=X7pL9qW3zT2rY8mF6vN4kJ5hB0cD1xA2uE3tR8w

